fix: fix updatepolicies
casbin/lua-casbin pull request #134
Opened 2021-10-03 09:45 UTC by Edmond-J-A

Fixed the problem that policies will in a wrong order after call function updatePolicies
Signed-off-by: Edmond-J-A <edomondja@gmail.com>

2021-10-03 10:51 UTC, rushitote approved these changes

2021-10-03 19:44 UTC, Edmond-J-A commented
Add a group of test unit and make it consist with casbin(go)

2021-10-04 13:44 UTC, techoner requested changes
@Edmond-J-A  Please format the code.

2021-10-05 02:30 UTC, techoner approved these changes

2021-10-05 02:30 UTC, merged