fix #157: split function accounting for quotes
casbin/lua-casbin pull request #158
Opened 2024-07-06 22:42 UTC by mikyll

Added Util.splitCSVLine() function that splits a CSV-formatted string into an array of tokens, accounting for quotes (single and double) and escape characters.

2024-07-06 22:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casbin/lua-casbin?pullRequest=158) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casbin/lua-casbin?pullRequest=158) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casbin/lua-casbin?pullRequest=158) it.</sub>

2024-07-07 01:25 UTC, hsluoyz commented
@mikyll fix CI errors:

![image](https://github.com/casbin/lua-casbin/assets/3787410/b16881d6-f140-4d5d-8f5e-17f8c1d30977)

2024-07-07 09:10 UTC, leeqvip requested changes

2024-07-07 09:10 UTC, leeqvip commented on src/util/Util.lua
> +end
Please add some unit tests

2024-07-08 22:00 UTC, mikyll commented
@leeqvip I made some fixes to Util functions and added unit tests for a use case about #157 (`{N,M}` regex quantifier)

2024-07-09 14:42 UTC, mikyll commented
# Summary

## Differences

### Old `Util.split(str, delimiter, x)` function

This function was used for simply splitting a CSV-formatted line, into an array of fields, separated by `delimiter` (up to x number of fields). Fields were also trimmed to remove leading/trailing whitespaces.

### New `Util.splitEnhanced(str, delimiter, trimFields)` function

This function does the same as `Util.split()`, but it adds the following features:
1. **quoted fields** - fields can be wrapped in double quotes (`"`) to escape comma characters that are part of the field (useful for example in regexMatch, to handle `{N,M}` pattern quantifiers);
2. **double quotes in quoted fields** - quoted fields can contain double quotes, which are escaped through another double quotes character (`""`).

    This complies with what is stated in the documentation ([Policy Storage | Casbin](https://casbin.org/docs/policy-storage)):
    
    <details>
    <summary>Show/Hide</summary>
    
    > **NOTE**
    > If your file contains commas, you should wrap them in double quotes. For example:
    > 
    > ```csv
    > p, alice, "data1,data2", read    --correct
    > p, alice, data1,data2, read        --incorrect (the whole phrase "data1,data2" should be wrapped in double quotes)
    > ```
    > 
    > If your file contains commas and double quotes, you should enclose the field in double quotes and double any embedded double quotes.
    > 
    > ```csv
    > p, alice, data, "r.act in (""get"", ""post"")"        --correct
    > p, alice, data, "r.act in ("get", "post")"            --incorrect (you should use "" to escape "")
    > ```
    > 
    > Related issue: [casbin#886](https://github.com/casbin/casbin/issues/886)

</details>

3. **policy syntax errors**:
    - if a quoted field presents extra trailing chracters, after the closing double quotes, the function throws the error `Quoted fields cannot have extra characters outside double quotes.`
    - if there are unmatched quotes, the function throws the error `Unmatched quotes.`

## New Example

- file `examples/basic_model_with_regex.conf` - implements a simple ACL model with regex for each field of the policy rules;
- file `examples/basic_policy_with_regex.csv` - shows a simple usage of this model with a rule that includes the pattern quantifier `{N,M}` (it includes a comma escaped through the **quoted field**, so it's a way to show the correct behaviour of the `Util.splitEnhanced()` function).

## Tests

### `util_spec`

- test **isOnlyWhitespaces** - verifies the correct behaviour of `Util.isOnlyWhitespaces()`;
- test **splitEnhanced** - verifies the correct behaviour of `Util.splitEnhanced()`. In particular, the usage of quotedFields, escaped double quotes and errors;

### `enforcer_spec`

- "regexMatch test" verifies the regexMatch behaviour of the new example, which exploits the new "quoted fields" feature.

2024-07-10 15:48 UTC, leeqvip approved these changes

2024-07-10 15:48 UTC, merged