feat: Added logging for requests and file logging functionality
casbin/lua-casbin pull request #54
Opened 2021-06-17 15:57 UTC by rushitote

- Now, there is a single logger for an Enforcer.
- Also added functionality to save all logs to a specific file.

2021-06-17 16:34 UTC, hsluoyz commented
@techoner

2021-06-18 10:19 UTC, rushitote commented
Added the `enforceEx` function and test for it.

2021-06-19 13:36 UTC, rushitote commented
Also added interfaces for Dispatcher and Watcher and tests for Watcher.

2021-06-23 04:10 UTC, techoner requested changes

2021-06-23 05:47 UTC, rushitote commented on src/main/CoreEnforcer.lua
> +end
@techoner I thought it would help to log to any file but since this isn't in any other Casbin implementation, should I remove it?

2021-06-23 05:51 UTC, rushitote commented on src/effect/DefaultEffector.lua
>      local result = true
Changed it to `false`.

2021-06-24 06:40 UTC, rushitote commented
@techoner Should I remove the logging to file function?

2021-06-24 15:44 UTC, techoner commented on src/main/CoreEnforcer.lua
> +end
@rushitote Yes, remove it, if you want to output the log to a file, you can use the log interface .

2021-06-24 17:29 UTC, rushitote commented on src/main/CoreEnforcer.lua
> +end
@techoner I have removed it.

2021-06-27 03:19 UTC, techoner approved these changes

2021-06-27 03:19 UTC, merged