feat: Add function newConfigFromText
casbin/lua-casbin pull request #79
Opened 2021-07-06 15:04 UTC by Edmond-J-A

feat: Add function newConfigFromText
Signed-off-by: 蒋振邦 <edomondja@gmail.com>

2021-07-06 16:56 UTC, hsluoyz commented
@rushitote plz review.

2021-07-06 18:01 UTC, rushitote requested changes

2021-07-07 01:23 UTC, hsluoyz commented
@Edmond-J-A remove:

![image](https://user-images.githubusercontent.com/3787410/124686014-ec2a7200-df04-11eb-855a-feb4209273db.png)

2021-07-07 08:20 UTC, Edmond-J-A reviewed
> @Edmond-JA删除：
> 
> ![图像](https://user-images.githubusercontent.com/3787410/124686014-ec2a7200-df04-11eb-855a-feb4209273db.png)

Removed， plz review

2021-07-07 08:56 UTC, merged